"""add_fitness_profile_fields

Revision ID: 6b71ba758f54
Revises: 545b19117910
Create Date: 2025-04-11 13:44:48.750683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b71ba758f54'
down_revision: Union[str, None] = '545b19117910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True))
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('goal', sa.Enum('LOSE_WEIGHT', 'GAIN_MUSCLE', 'GET_ENERGY', name='goal'), nullable=True))
    op.add_column('users', sa.Column('target_weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('diet', sa.Enum('NO_DIET', 'VEGAN', 'VEGETARIAN', name='diet'), nullable=True))
    op.add_column('users', sa.Column('experience', sa.Enum('NO_EXPERIENCE', 'LESS_THAN_YEAR', 'ONE_TO_THREE', 'MORE_THAN_THREE', name='experience'), nullable=True))
    op.add_column('users', sa.Column('workout_frequency', sa.Enum('ONE_TO_TWO', 'THREE_TO_FOUR', 'FOUR_TO_FIVE', 'SIX_TO_SEVEN', name='workoutfrequency'), nullable=True))
    op.drop_column('users', 'email_verification_token_expires')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'password_reset_token_expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verification_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verification_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'workout_frequency')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'diet')
    op.drop_column('users', 'target_weight')
    op.drop_column('users', 'goal')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
